name: generatebib

on: 
  workflow_dispatch
  schedule:
           - cron: '11 10 * * *'

jobs:
  bib`:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install ltd-conveyor

      - name: Generate bibfile
        run: |
          docker run --rm -v `pwd`:/workspace -w /lsst-texmf lsstsqre/lsst-texmf:latest sh -c 'make lsst.bib'


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WOM_UPDATEBIB_PAT }}
          branch: update-bibfile
          branch-suffix: short-commit-hash
          title: Automatic bibfile  update 
          commit-message: bibgile update
          body: Update bibfile from lsst.io and etc/static_entries.bib
